<?php

/*
 * Implements hook_menu()
 */
function user_edit_menu(){
  $path = drupal_get_path('module', 'user');
  $items['user/%user/edit/profile_settings'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title' => 'Profile Settings',
    'weight' => 1,
  );
  $items['user/%user/edit/information'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Information',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_edit_information_form',1),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'weight' => 2,
    'file path' => $path,
    'file' => 'user.pages.inc',
  );

  return $items;
}

/*
 * Implements hook_forms()
 */

function user_edit_forms($form_id, $args){
  $forms['user_edit_information_form'] = array(
    'callback' => 'user_profile_form',
  );
  $forms['user_edit_profile_settings_form'] = array(
    'callback' => 'user_profile_form',
  );
  return $forms;
}

/*
 * Implements hook_form_alter()
 */
function user_edit_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id){
    case 'user_edit_information_form' :
      $form['account']['#access']=FALSE;
      $form['picture']['#access']=FALSE;
      $form['overlay_control']['#access']=FALSE;
      $form['timezone']['#access']=FALSE;
      break;
    case 'user_edit_profile_settings_form':
      $form['field_name']['#access']=FALSE;
      $form['field_surname']['#access']=FALSE;
      $form['field_email']['#access']=FALSE;
      $form['field_about_me']['#access']=FALSE;
      $form['field_birthday']['#access']=FALSE;
      $form['picture']['#access']=FALSE;
      $form['overlay_control']['#access']=FALSE;
      $form['timezone']['#access']=FALSE;
      $form['account']['status']['#access']=FALSE;
      $form['account']['roles']['#access']=FALSE;
      $form['account']['notify']['#access']=FALSE;
      break;
  }
}

/*
 * Implements hook_menu_alter()
 */
function user_edit_menu_alter(&$items){
  $items['user/%user/edit'] = array_merge($items['user/%user/edit'], array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_edit_profile_settings_form', 1),
  ));
  $items['user/%user_category/edit/account']['access callback'] = FALSE;
}